//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unibox.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AppDarkMode {
            get {
                return ((bool)(this["AppDarkMode"]));
            }
            set {
                this["AppDarkMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InstallationInitialDirectory {
            get {
                return ((string)(this["InstallationInitialDirectory"]));
            }
            set {
                this["InstallationInitialDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemapToInitialDirectory {
            get {
                return ((string)(this["RemapToInitialDirectory"]));
            }
            set {
                this["RemapToInitialDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public double AppMainWidth {
            get {
                return ((double)(this["AppMainWidth"]));
            }
            set {
                this["AppMainWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("768")]
        public double AppMainHeight {
            get {
                return ((double)(this["AppMainHeight"]));
            }
            set {
                this["AppMainHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double AppInstallationsPgTopPanelHeight {
            get {
                return ((double)(this["AppInstallationsPgTopPanelHeight"]));
            }
            set {
                this["AppInstallationsPgTopPanelHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double AppInstallationsPgMidPanelHeight {
            get {
                return ((double)(this["AppInstallationsPgMidPanelHeight"]));
            }
            set {
                this["AppInstallationsPgMidPanelHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{Please set}")]
        public string SsUsername {
            get {
                return ((string)(this["SsUsername"]));
            }
            set {
                this["SsUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{Please set}")]
        public string SsPassword {
            get {
                return ((string)(this["SsPassword"]));
            }
            set {
                this["SsPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SsApiName {
            get {
                return ((string)(this["SsApiName"]));
            }
            set {
                this["SsApiName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SsApiUsername {
            get {
                return ((string)(this["SsApiUsername"]));
            }
            set {
                this["SsApiUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SsApiPassword {
            get {
                return ((string)(this["SsApiPassword"]));
            }
            set {
                this["SsApiPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ssThreads {
            get {
                return ((int)(this["ssThreads"]));
            }
            set {
                this["ssThreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseSsForRomAdds {
            get {
                return ((bool)(this["UseSsForRomAdds"]));
            }
            set {
                this["UseSsForRomAdds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StopRomAddOnNoScreenscraperMatch {
            get {
                return ((bool)(this["StopRomAddOnNoScreenscraperMatch"]));
            }
            set {
                this["StopRomAddOnNoScreenscraperMatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection SsRegionPriorities {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SsRegionPriorities"]));
            }
            set {
                this["SsRegionPriorities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51723")]
        public int MessagingPort {
            get {
                return ((int)(this["MessagingPort"]));
            }
            set {
                this["MessagingPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowOfflineGameUpdate {
            get {
                return ((bool)(this["AllowOfflineGameUpdate"]));
            }
            set {
                this["AllowOfflineGameUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BackupPlatformXml {
            get {
                return ((bool)(this["BackupPlatformXml"]));
            }
            set {
                this["BackupPlatformXml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int AppFontSize {
            get {
                return ((int)(this["AppFontSize"]));
            }
            set {
                this["AppFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int AppButtonPadding {
            get {
                return ((int)(this["AppButtonPadding"]));
            }
            set {
                this["AppButtonPadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double AppRomUploadWidth {
            get {
                return ((double)(this["AppRomUploadWidth"]));
            }
            set {
                this["AppRomUploadWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public double AppRomUploadHeight {
            get {
                return ((double)(this["AppRomUploadHeight"]));
            }
            set {
                this["AppRomUploadHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AddRomInitialDirectory {
            get {
                return ((string)(this["AddRomInitialDirectory"]));
            }
            set {
                this["AddRomInitialDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AppNavBarOpen {
            get {
                return ((bool)(this["AppNavBarOpen"]));
            }
            set {
                this["AppNavBarOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double AppPlatformDetailsHeight {
            get {
                return ((double)(this["AppPlatformDetailsHeight"]));
            }
            set {
                this["AppPlatformDetailsHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double AppPlatformDetailsWidth {
            get {
                return ((double)(this["AppPlatformDetailsWidth"]));
            }
            set {
                this["AppPlatformDetailsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int AppListPadding {
            get {
                return ((int)(this["AppListPadding"]));
            }
            set {
                this["AppListPadding"] = value;
            }
        }
    }
}
